// NFL Oracle v4.0 — Logistic Regression Meta-Model
// Loads coefficients + scaler from data/model/ (generated by python/train_model.py).
// Falls back to Monte Carlo win probability if model not trained yet.

import { readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../logger.js';
import type { FeatureVector } from '../types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const MODEL_DIR = resolve(__dirname, '../../data/model');

// Feature names in exact training order
export const FEATURE_NAMES = [
  'elo_diff',
  'pythagorean_diff',
  'win_pct_diff',
  'ppg_diff',
  'papg_diff',
  'net_ppg_diff',
  'yds_per_play_diff',
  'def_yds_per_play_diff',
  'turnover_diff_diff',
  'passer_rating_diff',
  'third_down_diff',
  'red_zone_diff',
  'injury_impact_diff',
  'qb_out_home',
  'qb_out_away',
  'rest_days_diff',
  'short_week_home',
  'short_week_away',
  'wind_adj',
  'precip_adj',
  'temp_adj',
  'altitude_adj',
  'divisional_game',
  'is_neutral',
  'vegas_home_prob',
  'mc_win_pct',
] as const;

interface ModelCoefficients {
  intercept: number;
  coefficients: number[];
  feature_names: string[];
}

interface ModelScaler {
  mean: number[];
  scale: number[];
  feature_names: string[];
}

interface CalibrationMap {
  x_thresholds: number[];
  y_thresholds: number[];
}

interface ModelMetadata {
  version: string;
  train_seasons: string;
  avg_brier: number;
  avg_accuracy: number;
  n_features: number;
  trained_at: string;
}

let _model: ModelCoefficients | null = null;
let _scaler: ModelScaler | null = null;
let _calibration: CalibrationMap | null = null;
let _metadata: ModelMetadata | null = null;

// ─── Load model artifacts ─────────────────────────────────────────────────────

export function loadModel(): boolean {
  const coeffPath = resolve(MODEL_DIR, 'coefficients.json');
  const scalerPath = resolve(MODEL_DIR, 'scaler.json');
  const calPath = resolve(MODEL_DIR, 'calibration.json');
  const metaPath = resolve(MODEL_DIR, 'metadata.json');

  if (!existsSync(coeffPath) || !existsSync(scalerPath)) {
    return false;
  }

  try {
    _model = JSON.parse(readFileSync(coeffPath, 'utf-8')) as ModelCoefficients;
    _scaler = JSON.parse(readFileSync(scalerPath, 'utf-8')) as ModelScaler;
    if (existsSync(calPath)) {
      _calibration = JSON.parse(readFileSync(calPath, 'utf-8')) as CalibrationMap;
    }
    if (existsSync(metaPath)) {
      _metadata = JSON.parse(readFileSync(metaPath, 'utf-8')) as ModelMetadata;
    }
    logger.info({ version: _metadata?.version, brier: _metadata?.avg_brier }, 'ML model loaded');
    return true;
  } catch (err) {
    logger.warn({ err }, 'Failed to load ML model — falling back to Monte Carlo');
    _model = null;
    _scaler = null;
    return false;
  }
}

export function isModelLoaded(): boolean {
  return _model !== null && _scaler !== null;
}

export function getModelInfo(): ModelMetadata | null {
  return _metadata;
}

// ─── Feature vector → array ───────────────────────────────────────────────────

function featureToArray(features: FeatureVector): number[] {
  return FEATURE_NAMES.map(name => {
    const val = features[name as keyof FeatureVector];
    return typeof val === 'number' ? val : 0;
  });
}

// ─── Standardize features ─────────────────────────────────────────────────────

function standardize(x: number[], scaler: ModelScaler): number[] {
  return x.map((val, i) => {
    const mean = scaler.mean[i] ?? 0;
    const scale = scaler.scale[i] ?? 1;
    return scale === 0 ? 0 : (val - mean) / scale;
  });
}

// ─── Sigmoid ─────────────────────────────────────────────────────────────────

function sigmoid(z: number): number {
  return 1 / (1 + Math.exp(-z));
}

// ─── Isotonic calibration ─────────────────────────────────────────────────────

function applyCalibration(prob: number, cal: CalibrationMap): number {
  const { x_thresholds, y_thresholds } = cal;
  if (prob <= x_thresholds[0]) return y_thresholds[0];
  if (prob >= x_thresholds[x_thresholds.length - 1]) return y_thresholds[y_thresholds.length - 1];

  for (let i = 1; i < x_thresholds.length; i++) {
    if (prob <= x_thresholds[i]) {
      const t = (prob - x_thresholds[i - 1]) / (x_thresholds[i] - x_thresholds[i - 1]);
      return y_thresholds[i - 1] + t * (y_thresholds[i] - y_thresholds[i - 1]);
    }
  }
  return prob;
}

// ─── Main predict function ────────────────────────────────────────────────────

export function predict(features: FeatureVector, mcWinPct: number): number {
  if (!_model || !_scaler) return mcWinPct;

  try {
    const rawFeatures = featureToArray(features);
    const scaled = standardize(rawFeatures, _scaler);

    // Logistic regression: z = intercept + sum(coef * feature)
    let z = _model.intercept;
    for (let i = 0; i < _model.coefficients.length; i++) {
      z += (_model.coefficients[i] ?? 0) * (scaled[i] ?? 0);
    }

    let prob = sigmoid(z);

    // Apply isotonic calibration if available
    if (_calibration) {
      prob = applyCalibration(prob, _calibration);
    }

    // Cap at 85%: no single NFL game is more predictable than this
    return Math.max(0.15, Math.min(0.85, prob));
  } catch (err) {
    logger.debug({ err }, 'ML predict error — falling back to Monte Carlo');
    return mcWinPct;
  }
}
